# Generated by Django 4.2.20 on 2025-04-14 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mivp', '0003_stage_delete_login_delete_register_tasks_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='default_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
