# Generated by Django 4.2.20 on 2025-04-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mivp', '0004_stage_default_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10),
        ),
    ]
