# Generated by Django 4.2.20 on 2025-04-16 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mivp', '0005_tasks_due_date_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='default_user',
            field=models.ForeignKey(blank=True, help_text='Usuario asignado por defecto a esta etapa', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mivp.projects'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='mivp.stage'),
        ),
    ]
