# Generated by Django 4.2.20 on 2025-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mivp', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='responsible_role',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('gerencia', 'Gerencia'), ('cliente', 'Cliente'), ('operaciones', 'Operaciones')], default='comercial', help_text='Rol que puede gestionar esta etapa', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('gerencia', 'Gerencia'), ('cliente', 'Cliente'), ('operaciones', 'Operaciones')], default='comercial', max_length=20),
        ),
    ]
