# Generated by Django 4.2.20 on 2025-04-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mivp', '0009_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
